version: "3"
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - environment.env
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: "mongo:latest"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"  
